###############################################
# Utilities
###############################################
cask "raycast"
cask "arc"
cask "vlc"
cask "tunnelblick"
cask "android-file-transfer"
cask "logi-options-plus"
cask "stats"


###############################################
# Development
###############################################

# Core apps
cask "docker"
cask "visual-studio-code"
cask "fork"
cask "iterm2"
brew "starship"
cask "google-chrome"

# Utilities
cask "provisionql"
cask "charles"
cask "http-toolkit"
cask "minisim"
brew "xcodes"
cask "kdiff3"
cask "vnc-viewer"
cask "microsoft-remote-desktop"
cask "azure-data-studio"
brew "tlrc"
brew "jq"

# React-Native
brew "rbenv"
tap "homebrew/cask-versions"
cask "zulu17"
brew "watchman"
cask "zulu11" # For RN v0.68
cask "android-studio"
cask "react-native-debugger"

# Python
brew "pyenv"
cask "pycharm-ce"

###############################################
# Personal
###############################################

cask "spotify"
cask "keepassxc"
cask "whatsapp"
cask "gimp"
cask "discord"
brew "onedrive"
cask "messenger"

tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"


##############################################
# VSCode plugins
###############################################

# Background / IDE utilities
vscode "asciidoctor.asciidoctor-vscode"
vscode "EditorConfig.EditorConfig"
vscode "streetsidesoftware.code-spell-checker"
vscode "naumovs.color-highlight"
vscode "artdiniz.quitcontrol-vscode"
vscode "mechatroner.rainbow-csv"
vscode "ionutvmi.path-autocomplete"

# Frontend development
vscode "formulahendry.auto-close-tag"
vscode "nrwl.angular-console"
vscode "YoavBls.pretty-ts-errors"
vscode "codeandstuff.package-json-upgrade"
vscode "dbaeumer.vscode-eslint"
vscode "firsttris.vscode-jest-runner" # running or debugging a specific test or test-suite
vscode "Orta.vscode-jest" # running your current test-suite everytime you change it.

# Native development
vscode "mathiasfrohlich.Kotlin"

# Tools
vscode "adpyke.codesnap"
vscode "pomdtr.excalidraw-editor"
vscode "ctcuff.font-preview"
vscode "tomoki1207.pdf"
vscode "jock.svg"
vscode "george-alisson.html-preview-vscode"
vscode "eriklynd.json-tools"

# Copilot
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"

# Git
vscode "mhutchie.git-graph"
vscode "eamodio.gitlens"

# Markdown
vscode "yzhang.markdown-all-in-one"
vscode "bierner.markdown-mermaid"
vscode "TakumiI.markdowntable"
vscode "DavidAnson.vscode-markdownlint"

# Themes
vscode "zhuangtongfa.material-theme"
vscode "PKief.material-icon-theme"
vscode "johnpapa.vscode-peacock"
